### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stdin' of undefined

### ISSUE THREAD

**Issue by aponski** [lukehoban/atom-ide-flow#26]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.3
**Thrown From**: [ide-flow](https://github.com/lukehoban/atom-ide-flow) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'stdin' of undefined

```
At /Users/arkadiuszponski/.atom/packages/ide-flow/lib/util-flow-command.coffee:30

TypeError: Cannot read property 'stdin' of undefined
  at run (/Users/arkadiuszponski/.atom/packages/ide-flow/lib/util-flow-command.coffee:30:28)
  at Object.module.exports.typeAtPos (/Users/arkadiuszponski/.atom/packages/ide-flow/lib/util-flow-command.coffee:73:5)
  at PluginManager.typeAtPos (/Users/arkadiuszponski/.atom/packages/ide-flow/lib/plugin-manager.coffee:63:21)
  at EditorControl.showExpressionType (/Users/arkadiuszponski/.atom/packages/ide-flow/lib/editor-control.coffee:91:14)
  at /Users/arkadiuszponski/.atom/packages/ide-flow/lib/editor-control.coffee:37:10

```

### Commands

```
  4x -2:01.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-seti-ui)
     -1:00.7.0 core:confirm (atom-text-editor.editor.mini)
     -0:44 ide-flow:check (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-seti-ui)
     -0:08.7.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-seti-ui)
     -0:03.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.1.0 ide-flow:check (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter",
      "todo-list"
    ],
    "themes": [
      "seti-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "ide-flow": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.12.0
emmet, v2.3.8
ide-flow, v0.2.0
lesscompile, v0.5.0
linter-flow, v0.1.4
linter-jsxhint, v0.1.1
react, v0.11.7
seti-ui, v0.6.3
synced-sidebar, v0.2.3

# Dev
No dev packages
```

**Comment by lukehoban** [comment]
This should be fixed in the v0.3.0 release that was pushed this morning.

**Comment by rpominov** [comment]
Hi, I'm still getting a similar error.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.200.0
**System**: Mac OS X 10.10.3
**Thrown From**: [ide-flow](https://github.com/lukehoban/atom-ide-flow) package, v0.6.0


### Stack Trace

Uncaught TypeError: Cannot read property 'stdin' of undefined

```
At /Users/anon/.atom/packages/ide-flow/lib/util-flow-command.coffee:37

TypeError: Cannot read property 'stdin' of undefined
  at run (/Users/anon/.atom/packages/ide-flow/lib/util-flow-command.coffee:37:28)
  at Object.module.exports.typeAtPos (/Users/anon/.atom/packages/ide-flow/lib/util-flow-command.coffee:77:5)
  at PluginManager.typeAtPos (/Users/anon/.atom/packages/ide-flow/lib/plugin-manager.coffee:63:21)
  at EditorControl.showExpressionType (/Users/anon/.atom/packages/ide-flow/lib/editor-control.coffee:91:14)
  at /Users/anon/.atom/packages/ide-flow/lib/editor-control.coffee:37:10

```

### Commands

```
     -3:03.3.0 ide-flow:check (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-atom-light-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "dev-live-reload",
      "language-objective-c",
      "language-go",
      "language-c",
      "language-java",
      "language-mustache",
      "language-perl",
      "language-php",
      "language-sql",
      "metrics"
    ]
  },
  "ide-flow": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.17.1
ide-flow, v0.6.0

# Dev
No dev packages
```

**Comment by rpominov** [comment]
Also can be fixed by specifying Flow Path in the settings. Although `flow` was in my PATH already.

**Comment by jonsmithers** [comment]
Ah, I'm glad Google led me here. I was getting this issue today, and @rpominov's tip got things working. This is my first install of this package.

**Comment by ColCh** [comment]
@rpominov Thank you, helped me too. Flow is installed via _homebrew_.

**Comment by pelotom** [comment]
It would be nice if this package looked for flow in the `node_modules/.bin` at the root of the project, or at least let me set a path that was relative to the project root. It's very standard to install flow as a dev dependency rather than globally.
